### ISSUE TITLE
How to integrate the library in a Swift project.

### ISSUE THREAD

**Issue by preetigaur** [dsprenkels/sss#13]

**Comment by dsprenkels** [comment]
Hey @preetigaur, could you elaborate a bit on this issue? At this moment the sss library is untested on iOS (I do not own such a device), but if there are any issues I would really like to have them fixed.

**Comment by preetigaur** [comment]
Hi 
Sorry I am facing different issue in iOS. Could you please provide the steps as to how can I integrate the library in an existing swift project? I can't really integrate the library. Your help is appreciated. Thanks in Advance.

**Comment by dsprenkels** [comment]
So currently I do not have access to an Apple dev machine. I am also really not experienced with Swift development at all. If I remember correctly, when I built the [Swift bindings](https://github.com/dsprenkels/sss-swift) I have tried to follow the packaging guidelines mentioned in the Swift docs.

I have included a [`Package.swift`](https://github.com/dsprenkels/sss-swift/blob/master/Package.swift) file. Have you already tried the instructions listed at https://swift.org/package-manager/#importing-dependencies?

**Comment by dsprenkels** [comment]
By the way. Because I am not really capable of dev'ing Swift with my current setup, I would really appreciate any help (if you can spare the effort).

**Comment by preetigaur** [comment]
Ok. I'll try to integrate the Bindings in the Swift project. Were you successfully able to build the project because I keep on getting error of module not found "libsss".

**Comment by dsprenkels** [comment]
The `sss` library is located in a git submodule. Did you already do:
```
git submodule init
git submodule update
```

**Comment by dsprenkels** [comment]
This seems to work in my case (I used the Docker container at https://hub.docker.com/_/swift/):

```
root@3768da4f1fe1:~# git clone --recursive https://github.com/dsprenkels/sss-swift.git
Cloning into 'sss-swift'...
remote: Counting objects: 47, done.
remote: Total 47 (delta 0), reused 0 (delta 0), pack-reused 47
Unpacking objects: 100% (47/47), done.
Checking connectivity... done.
Submodule 'sss' (https://github.com/dsprenkels/sss.git) registered for path 'sss'
Cloning into 'sss'...
remote: Counting objects: 416, done.
remote: Total 416 (delta 0), reused 0 (delta 0), pack-reused 416
Receiving objects: 100% (416/416), 81.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (268/268), done.
Checking connectivity... done.
Submodule path 'sss': checked out '17b0c6f4fb5d5427d75d7b3d2c39b0b286da2f47'
Submodule 'randombytes' (https://github.com/dsprenkels/randombytes.git) registered for path 'randombytes'
Cloning into 'randombytes'...
remote: Counting objects: 118, done.
remote: Total 118 (delta 0), reused 0 (delta 0), pack-reused 118
Receiving objects: 100% (118/118), 20.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (59/59), done.
Checking connectivity... done.
Submodule path 'sss/randombytes': checked out '73ae9b4fce2e62babdd6a480b53ad449dd745ed9'
root@3768da4f1fe1:~# cd sss-swift/
root@3768da4f1fe1:~/sss-swift# swift build
Compile libsss hazmat.c
Compile libsss tweetnacl.c
Compile libsss sss.c
Compile libsss randombytes.c
/root/sss-swift/Sources/libsss/randombytes.c:172:11: warning: Using getrandom system call [-W#pragma-messages]
#  pragma message("Using getrandom system call")
          ^
1 warning generated.
Compile Swift Module 'ShamirSecretSharing' (1 sources)
Linking ./.build/x86_64-unknown-linux/debug/ShamirSecretSharing
```

**Comment by dsprenkels** [comment]
Closing as a stale issue.
