### ISSUE TITLE
Python and JS wrapper

### ISSUE THREAD

**Issue by DonaldTsang** [dsprenkels/sss#25]
Might be useful for people who wants to play around with SSSS

**Comment by dsprenkels** [comment]
A javascript wrapper should be possible, if you compile the code with something like emscripten. Moreover, we do have [support](https://github.com/dsprenkels/sss-node) for Node.js

I would really be happy with a Python implementation, but I do not have time to implement this myself. However, there is already a tracking issue: #3.
