### ISSUE TITLE
Notes on blockstack/secret-sharing

### ISSUE THREAD

**Issue by DonaldTsang** [dsprenkels/sss#29]
It does not use GF(256) or other GF(2^n) unlike sss and others.
Something worth while to note.
Also
- https://github.com/SSSaaS
- https://github.com/ronreiter/multicrypt (Python)
- https://github.com/klingebj/shamir_bip39_2039 (Python)
- https://github.com/seancomeau/ShamirSecretSharing (Python)
- https://github.com/szymekk/shamirs_secret_sharing (Python)
- https://github.com/pcrain/pyshamir (Python)
- https://github.com/myd1/Shamir-s-Secret-Sharing (Python)
- https://github.com/nijynot/shamir (JS)
- https://github.com/mdciotti/polypass (JS)
- https://github.com/agl/shamirsplit (Go)
- https://github.com/itslab-kyushu/sss (Go)
- https://github.com/iowaguy/shamir-secret-sharing (Go)
- https://github.com/republicprotocol/shamir-go (Go)
- https://github.com/amousa11/sss (Go)

has this feature. (have not checked C or C++)

**Comment by dsprenkels** [comment]
Hi. Sorry for reacting this late. I think I do not fully understand your comment.

> It does not use GF(256) or other GF(2^n) unlike sss and others.

Yeah. This is a design choice. I am not really sure why this would matter. 

> Also [...] has this feature. (have not checked C or C++)

What feature are you referring to? Are you referring to using GF(p), instead of GF(2^n)?

**Comment by DonaldTsang** [comment]
@dsprenkels the reason whether GF(p) and GF(2^8) is due to efficiency and code simplicity
- GF(p) is easier to implement, can have p-1 shares, but lightly slower
- GF(2^8) is slightly harder to implement, faster, but can only have 255 shares

**Comment by dsprenkels** [comment]
Yeah. What about it? I don't really seem to get what is the issue/bug we need to solve.

**Comment by DonaldTsang** [comment]
@dsprenkels would like to add these extra footnotes on the ReadMe

**Comment by dsprenkels** [comment]
Oh. Of course. :)

You are completely welcome to. Just open a pull request.
