### ISSUE TITLE
Error while executing makefile

### ISSUE THREAD

**Issue by helderduartemop** [dsprenkels/sss#32]
I've been trying to run your makefile, and as soon as I've cloned your git, I have then tried running the make command, but I keep on getting the error that there's no file or directory named sys/syscall.h (included in the randombytes.c and randombytes.h files).

**Comment by dsprenkels** [comment]
Hmmm. I think `sys/syscall.h` should be generally present on unix systems. What system are you running?

**Comment by helderduartemop** [comment]
I was running on a Virtual Machine with 64-bit Ubuntu, apparently that was a big part of the issue, as I've tried it later on a native Ubuntu system and it worked properly.

**Comment by dsprenkels** [comment]
Ok. I'll mark this issue as resolved for now. If you know which ubuntu package contained the `sys/syscall.h` file, I'd like to know. Then I can add it to the `README.md`.
