### ISSUE TITLE
Question: does this library support feldman verifiable sss ?

### ISSUE THREAD

**Issue by shoppertreat** [dsprenkels/sss#37]
hi,
  could not see how else to address this question. hence filing an issue. How can i use the library to use verifiable sss using feldman approach of homomorphic encryption ?
  thanks,
regards,
Nilay

**Comment by dsprenkels** [comment]
Dear @shoppertreat,

Indeed this libary does not support Feldman VSS (and it is considered not in scope for this library). At this moment, I have no recommendations for alternative software to use, sorry.

 -- Daan
